version: "3"
services:

  notification_microservice:
    build: ./notification_microservice
    ports:
    - "3000:3000"
    networks:
      - event_booking_microservices

  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
 
networks:
  postgres:
    driver: bridge
  microservices:
    driver: event_booking_app